name: build
on:
  workflow_dispatch: {}
  push:
    branches:
      - release-*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as the cache uses the current rustc version as its cache key
      - run: rustup toolchain install stable --profile minimal
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build binary
        run: cargo build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          # name: build_${{ github.sha }}
          path: target/debug/example-workflow-artifacts
      - name: List the files in this directory
        run: ls -al
      - name: Run the binary
        run: ./target/debug/example-workflow-artifacts