name: download-and-run
on:
  workflow_dispatch: {}
  pull_request:

jobs:
  download_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      # Get the workflow run that has the latest build for release-1 branch.
      - name: Get the latest build
        id: get_latest_workflow_run_id_release_1
        # Set the stdout of running `cd ci_utils && cargo run --bin get_latest_workflow_run build release-1` to the output of this step.
        run:
          echo "LATEST_WORKFLOW_RUN_ID=$(cd ci_utils && cargo run --bin get_latest_workflow_run build release-1)" >> "$GITHUB_OUTPUT"
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
      - name: Download the latest build
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ steps.get_latest_workflow_run_id_release_1.outputs.LATEST_WORKFLOW_RUN_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: List the files in this directory
        run: ls -al
      - name: List the files in the downloaded artifact
        run: ls -al artifact
      - name: Run the binary
        run: ./artifact
      # - name: Get the latest commit SHA
      #   id: get_latest_commit_sha_release_1
      #   run: echo "COMMIT_SHA=$(cd ci_utils && cargo run --bin get_target_branch_commit_hash release-1)" >> "$GITHUB_OUTPUT"
      # - name: Create target/debug directory
      #   run: mkdir -p target/debug
      # # - name: Unzip the downloaded artifact
      # #   run: unzip build_${{ steps.get_latest_commit_sha_release_1.outputs.COMMIT_SHA }} -d target/debug/
      # - name: Move the downloaded artifact
      #   run: mv build_${{ steps.get_latest_commit_sha_release_1.outputs.COMMIT_SHA }} target/debug/build_${{ steps.get_latest_commit_sha_release_1.outputs.COMMIT_SHA }}
      # - name: List the files in the target/debug directory
      #   run: ls -al target/debug
      # # - name: Rename the downloaded artifact
      # #   run: mv target/debug/example-workflow-artifacts target/debug/build_${{ steps.get_latest_commit_sha_release_1.outputs.COMMIT_SHA }}
      # - name: Enable execute permission
      #   run: chmod +x target/debug/build_${{ steps.get_latest_commit_sha_release_1.outputs.COMMIT_SHA }}
      # - name: Run the downloaded binary
      #   run: ./target/debug/build_${{ steps.get_latest_commit_sha_release_1.outputs.COMMIT_SHA }}