name: download-and-run
on:
  workflow_dispatch: {}
  pull_request:

jobs:
  download_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Git Branches
        run: |
          git branch --remotes
          git --version
          git branch -al 'origin/release-branch-2024-03-22'
      # Get the workflow run that has the build for the latest release-branch-* branch.
      - name: Get the latest build
        id: get_latest_workflow_run_id_release_branch
        run:
          echo "LATEST_WORKFLOW_RUN_ID=$(cd ci_utils && cargo run --bin get_latest_workflow_run 'origin/release-branch-*')" >> "$GITHUB_OUTPUT"
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the latest commit SHA
        id: get_latest_commit_sha_release_branch
        run: echo "COMMIT_SHA=$(cd ci_utils && cargo run --bin get_target_branch_commit_hash 'origin/release-branch-*')" >> "$GITHUB_OUTPUT"
      - name: Download the latest build
        uses: actions/download-artifact@v4
        with:
          name: build_${{ steps.get_latest_commit_sha_release_branch.outputs.COMMIT_SHA }}
          run-id: ${{ steps.get_latest_workflow_run_id_release_branch.outputs.LATEST_WORKFLOW_RUN_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create target/debug directory
        run: mkdir -p target/debug
      - name: Move the downloaded artifact
        run: mv example-workflow-artifacts target/debug/build_${{ steps.get_latest_commit_sha_release_branch.outputs.COMMIT_SHA }}
      - name: Enable execute permission for the binary
        run: chmod +x ./target/debug/build_${{ steps.get_latest_commit_sha_release_branch.outputs.COMMIT_SHA }}
      - name: Run the downloaded binary
        run: ./target/debug/build_${{ steps.get_latest_commit_sha_release_branch.outputs.COMMIT_SHA }}